### ISSUE TITLE
What is the get request format?

### ISSUE THREAD

**Issue by umran** [aharen/Pay#2]
I understand that once get() is called it returns a list of parameters along with the signature. I'm just curious, what would be the format of the get request (assuming it is a get request)? What are the parameter names?

**Comment by aharen** [comment]
Hi. 

The get() method simply returns an array with all your config based on your Payment Gateway Provider. It's not a request but a method call to the provider being used.  Please take a look at [https://github.com/aharen/Pay/blob/master/src/Providers/AbstractProvider.php](url) 

A for the parameter names, please take a look the providers in [https://github.com/aharen/Pay/tree/master/src/Providers](url)

Hope this answers your question :)

Cheers

**Comment by umran** [comment]
Thanks for the prompt response. I guess what I really wanted to ask is, what sort of request does the bank endpoint expect with the transaction? I assume the parameters returned by the get() method are used in some sort of POST or GET request that the client makes to the bank's server. What would that request look like?

Also, do you know the format and length of MerSecret, that is, anything pertaining to what is considered a valid MerSecret?

Thanks again!

**Comment by aharen** [comment]
Oh i see, sorry i misunderstood the question. Both banks (BML and  MIB) requires that you POST the data to their gateway.

By MerSecret do you mean MerPassword? If so, it is provided from the Bank in question which, as far as i am aware, can only be modified by Bank. (I could be wrong about the changing of MerPassword)

If you'd like to test out the script take a look at [https://pay.mv](url) It's a mock gateway.

Cheers

**Comment by umran** [comment]
Hey no worries. And thanks for pointing me to the mock gateway. Really appreciate it.

Cheers!
